#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2
# and facebook.com to resolve to 8.8.8.8

cat <<EOF | sudo tee /etc/hosts > /dev/null
127.0.0.1   ubuntu
127.0.0.2   localhost
8.8.8.8     facebook.com
EOF
