#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2
# and facebook.com to resolve to 8.8.8.8

sudo sed -i '/127.0.0.1\s*localhost/s/.*/127.0.0.2\tlocalhost/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
